modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/aojiangQAQ/itemraritygui/issues"
displayURL = "https://shuguang.space"

[[mods]]
modId = "itemraritygui"
version = "1.0"
displayName = "物品稀有度背景显示"
displayURL = "https://shuguang.space"
logoFile = "team.png"
authors = "aojiangQAQ（鳌江）, 曙光团队"
description = '''
由 aojiangQAQ（鳌江）与曙光团队制作。
为物品栏及背包中的物品添加美观的稀有度背景颜色。
'''

[[dependencies.itemraritygui]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.itemraritygui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"
